name: Blue Bunny Job Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar archivos
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Restaurar memoria
        uses: actions/cache@v4
        with:
          path: seen_jobs.json
          key:  blue-bunny-jobs-memory
          restore-keys: |
            blue-bunny-jobs-

      - name: Ejecutar bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python bot.py

      - name: Guardar memoria
        uses: actions/upload-artifact@v4
        with:
          name: seen-jobs
          path: seen_jobs.json
          overwrite: true
