name: Blue Bunny Job Alert

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar archivos
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar requests
        run: pip install requests

      - name: Ejecutar bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python bot.py
